# docker-compose.yml
version: '3.8'

services:
  nextapp:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./.next:/app/.next
    restart: unless-stopped
